# -*- python -*-
# This file was automatically generated
# Do NOT edit this file when using the Eclipse SconsBuilder plugin!
# The Eclipse SconsBuilder plugin WILL overwrite this file!

BASE_VARIANT_DIR = '.build'

BUILD_CONFIGURATIONS = []
BUILD_CONFIGURATION = None

BUILD_TARGETS = []
BUILD_TARGET = None

BIN_DIR = 'bin'
LIB_DIR = 'lib'
DOC_DIR = 'doc'

DOXYGEN_CONFIGFILE = 'doxygen.cfg'

UNITTEST_ENABLED = False
UNITTEST_DIR_NAME = 'test' 
UNITTEST_TEST_PREFIX = 'test-' 
UNITTEST_LIB_PREFIX = 'test-' 
UNITTEST_INCLUDE_DIR = ''
UNITTEST_LIB_DIR = ''
UNITTEST_LIB = ''
UNITTEST_TESTRUNNER = ''

SKIP_DIRS = ['.*', 'CVS', 'bin', 'lib', 'doc']

CXX_GLOB = ['*.c', '*.cc', '*.cpp', '*.cxx']

SCONSBUILDER_CONFIG_FILE_NAME = '.scb'

