# -*- python -*-
#/******************************************************************************
# * Copyright (c) 2004, 2009 Lothar Werzinger.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *****************************************************************************/ 
#
# !!! This file was automatically generated !!!
# Do NOT edit this file when using the Eclipse SconsBuilder plugin!
# The Eclipse SconsBuilder plugin WILL overwrite this file!

BASE_VARIANT_DIR = '.build'

BUILD_CONFIGURATIONS = ['release', 'debug', 'coverage']
BUILD_CONFIGURATION = 'release'

BUILD_TARGETS = []
BUILD_TARGET = ''

BIN_DIR = 'bin'
LIB_DIR = 'lib'
DOC_DIR = 'doc'

DOXYGEN_CONFIGFILE = 'doxygen.cfg'

UNITTEST_ENABLED = False
UNITTEST_DIR_NAME = 'test'
UNITTEST_TEST_PREFIX = 'test-'
UNITTEST_LIB_PREFIX = 'test-'
UNITTEST_INCLUDE_DIR = '/usr/local/include'
UNITTEST_LIB_DIR = '/usr/local/lib'
UNITTEST_LIB = 'cppunit'
UNITTEST_TESTRUNNER = ''

SKIP_DIRS = ['.*', 'CVS', 'bin', 'lib', 'doc']

CXX_GLOB = ['*.c', '*.cc', '*.cpp', '*.cxx']

SCONSBUILDER_CONFIG_FILE_NAME = '.scb'

