import os

Import('env')
Import('gini_home')

gbuilder_files = Split("""
    Core
    Devices
    images
    Network
    UI""")

#if env['PLATFORM'] == 'win32':
#    linkCmd = "mklink $TARGET $SOURCE"
#else:
#    linkCmd = "ln $SOURCE $TARGET"
env.Install(gini_home + '/share/gbuilder', 'gbuilder.py')

for x in gbuilder_files:
  env.Install(gini_home + '/share/gbuilder/' + x, Glob(x + "/*.py"))
if env['PLATFORM'] != 'win32':
    env.Command(gini_home + '/bin/gbuilder', gini_home + '/share/gbuilder/gbuilder.py', "ln -s $SOURCE $TARGET")
env.Alias('install', gini_home + '/share/gbuilder')

